# SPDX-FileCopyrightText: 2026 Sergei Mukhin
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "edible-css"
SPDX-PackageSupplier = "Sergei Mukhin <sergei_mukhin@outlook.com>"
SPDX-PackageDownloadLocation = "https://github.com/svmukhin/edible-css"

[[annotations]]
path = [
  "dist/**",
  "package-lock.json",
  "test/backstop/test/**",
  "test/backstop/reference/**",
  "node_modules/**",
  ".gitignore",
  "package.json",
  ".markdownlint-cli2.yaml",
  "backstop.json",
  "test/backstop/backstop.json",
  ".pa11yci.json",
  "**.md",
  "docs/**.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Sergei Mukhin"
SPDX-License-Identifier = "MIT"
